version: '3'
services:
  web:
    build: .
    command: /bin/bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

  db:

    image: "postgres:latest"
    environment:
      POSTGRES_DB: adrress_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lover1999
    ports:
      - "5433:5432"
    networks:
      - my_network

networks:
      my_network:
        driver: bridge