# Generated by Django 4.2.4 on 2023-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "contacts",
                    models.ManyToManyField(
                        related_name="contact_groups", to="contact.contact"
                    ),
                ),
            ],
        ),
    ]
